name: Publish Package to npmjs
on:
 release:
   types: [created]

jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     id-token: write
   steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: '18.x'
        # required for credentials to be taken in account
        registry-url: 'https://registry.npmjs.org'
    - name: Install latest npm
      run: npm install -g npm
    - name: Install
      run: yarn install
    - name: Test
      run: yarn test
    - name: Publish
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
